name: neverending-story

on:
  workflow_dispatch:

jobs:
  delay-and-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: |
          sleep 30

      - name: Dispatch next workflow run
        uses: benc-uk/workflow-dispatch@v1.2.3
        with:
          workflow: "neverending-story.yaml"
